### ISSUE TITLE
Find commits by name in massive repo?

### ISSUE THREAD

**Issue by the-r3dacted** [neodyme-labs/github-secrets#4]
I'm trying to find some commits from mozilla/gecko-dev. I tried the program, but it listed a bunch of pretty recent commits that I don't have any interest in. (The oldest being from three days ago)

Basically I'd like to take these commits from the Mercurial repository and find the corresponding ones on GitHub.

https://hg.mozilla.org/releases/mozilla-release/rev/FIREFOX_RELEASE_117_END

https://hg.mozilla.org/releases/mozilla-release/rev/FIREFOX_RELEASE_118_END

https://hg.mozilla.org/releases/mozilla-release/rev/FIREFOX_RELEASE_119_END

https://hg.mozilla.org/releases/mozilla-release/rev/FIREFOX_RELEASE_120_END

https://hg.mozilla.org/releases/mozilla-release/rev/FIREFOX_RELEASE_121_END

All of these have a relatively unique name where there may only be a few commits with the same exact name. I would like to be able to search for the name and see if I can find them. They should still exist on GitHub as I was able to find the release 122 commit not linked to a branch.

**Comment by the-r3dacted** [comment]
A solution for my problem was to do https://github.com/mozilla/gecko-dev/tree/release@%7B202x-xx-xx%7D and input dates for the respective tags to find the commits. That worked just fine. However I do think the tool could still be improved for large repos in the case it's a bit harder to find than this.

**Comment by gcm-explo1t** [comment]
This tool has a different purpose. You are searching for commits in a repository at a certain time. This tool finds commits that are not in the git history at all.
